---
title: "Final Project"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
library(Hmisc)
library(DT)
library(ggplot2)

library(data.table)
assignInNamespace("cedta.override", c(data.table:::cedta.override,"rmarkdown"), "data.table")


opts_chunk$set(echo = FALSE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55), tidy = TRUE)

```


```{r read_data}
dat <- fread(input = "../Data/winemag-data-130k-v2.csv", verbose = FALSE,na.strings=c(""))
dat <- dat[,2:14]

```


```{r constants}
country.name <- "country"
description.name <- "description"           
designation.name <- "designation"           
points.name <- "points"               
price.name <- "price"                 
province.name <- "province"              
region_1.name <- "region_1"              
region_2.name <- "region_2"             
taster.name <- "taster_name"           
twitter.name <- "taster_twitter_handle" 
title.name <- "title"                 
variety.name <- "variety"              
winery.name <- "winery"               

dat[,eval(points.name)] <- as.numeric(dat[,get(points.name)])
dat[,eval(price.name)] <- as.numeric(dat[,get(price.name)])

single.var <- c(points.name, price.name, country.name)


```

```{r functions}
percentage.table <- function(x, digits = 1){
  tab <- table(x)
  percentage.tab <- 100*tab/(sum(tab))
  rounded.tab <- round(x = percentage.tab, digits = digits)
  return(rounded.tab)
}

round.numerics <- function(x, digits){
  if(is.numeric(x)){
    x <- round(x = x, digits = digits)
  }
  return(x)
}
miss.value <- function(x){
  miss.rate <- round(100*mean(is.na(x)),2)
  return(miss.rate)
}
```


Introduction
=====================================  


Click on the tabs to see different reports.


Missing Value
===================================


Row {data-height=500}
-------------------------------------

```{r respondents}
inputPanel(
  
)

renderPlot({
  tab <- t(dat[,lapply(X=.SD,FUN="miss.value")])
  
  tab2 <- data.table(var=names(dat),miss=as.numeric(tab))
  barplot(height=tab2$miss, names.arg=tab2$var,space=0.01, las=1,
          main="Missing Rate",ylab="Percentage", ylim=c(0,100),col="dodgerblue")
  text(x = -0.5 + 1.02*1:tab2[, .N], y = -15, labels = tab2$var,srt = 45, cex = 1, pos = 2)
  space_val=0
  text(x=-0.4+1:length(tab)*(1+space_val),y=tab,labels=sprintf("%.1f%%",tab),pos=3)
})
```

Variable Information
=====================================  


Row {data-height=800}
-------------------------------------

```{r products}
inputPanel(
  selectInput(inputId = "var_info", label = "Variavles:",
              choices = single.var, selected = single.var[1]),
  checkboxInput(inputId = "by_country", label = "Shown by Country:", value = FALSE)
)

renderPlot({
  if (input$by_country == FALSE){
    plot(x=1:length(sort(dat[,get(input$var_info)])),y=sort(dat[,get(input$var_info)]), 
       main=sprintf("Distribution of %s",input$var_info),
       xlab="", ylab=input$var_info, col="dodgerblue")
  }
  if (input$by_country == TRUE){
    tem <- dat[,.(N=.N,Mean=mean(get(input$var_info),na.rm=T),
                  Var=var(get(input$var_info),na.rm=T)),by=country.name]
    tem <- tem[tem$N >= 100,]
    setorderv(tem, col="Mean",order=1)
    par(mfrow=c(1,2))
    barplot(tem$Mean-(round(min(tem$Mean))-2), 
            main=sprintf("Mean of %s by Country",input$var_info),
            ylab="Country", xlab=input$var_info, col="dodgerblue",horiz=TRUE,
            names.arg = tem$country,cex.names = 1,las = 1,
            xlim=c(round(min(tem$Mean))-2,round(max(tem$Mean))+2), 
            offset = min(round(min(tem$Mean))-2))
    #axis(1,min(tem$Mean)-2:100, min(tem$Mean)-2:100, las = 1)
    barplot(tem$Var-(min(tem$Var)-1), 
            main=sprintf("Variance of %s by Country",input$var_info),
            ylab="Country", xlab=input$var_info, col="dodgerblue",horiz=TRUE,
            names.arg = tem$country,cex.names = 1,las = 1,
            xlim=c(min(tem$Var)-1,max(tem$Var)),offset = min(tem$Var-1))
  }
})
```

