---
title: "Final Project"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
library(Hmisc)
library(DT)
library(ggplot2)

library(data.table)
assignInNamespace("cedta.override", c(data.table:::cedta.override,"rmarkdown"), "data.table")


opts_chunk$set(echo = FALSE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55), tidy = TRUE)

```


```{r read_data}
dat <- fread(input = "../Data/winemag-data-130k-v2.csv", verbose = FALSE,na.strings=c(""))
dat <- dat[,2:14]

```


```{r constants}
country.name <- "country"
description.name <- "description"           
designation.name <- "designation"           
points.name <- "points"               
price.name <- "price"                 
province.name <- "province"              
region_1.name <- "region_1"              
region_2.name <- "region_2"             
taster.name <- "taster_name"           
twitter.name <- "taster_twitter_handle" 
title.name <- "title"                 
variety.name <- "variety"              
winery.name <- "winery"               

dat[,eval(points.name)] <- as.numeric(dat[,get(points.name)])
dat[,eval(price.name)] <- as.numeric(dat[,get(price.name)])

single.var <- c(points.name, price.name, country.name)


```

```{r functions}
percentage.table <- function(x, digits = 1){
  tab <- table(x)
  percentage.tab <- 100*tab/(sum(tab))
  rounded.tab <- round(x = percentage.tab, digits = digits)
  return(rounded.tab)
}

round.numerics <- function(x, digits){
  if(is.numeric(x)){
    x <- round(x = x, digits = digits)
  }
  return(x)
}
miss.value <- function(x){
  miss.rate <- round(100*mean(is.na(x)),2)
  return(miss.rate)
}
percentage.cal <- function(x, digits = 3){
  
  percentage.tab <- 100*x/47432
  rounded.tab <- round(x = percentage.tab, digits = digits)
  return(rounded.tab)
}
```


Introduction
=====================================  


Click on the tabs to see different reports.


Missing Value
===================================


Row {data-height=500}
-------------------------------------

```{r respondents}
inputPanel(
  
)

renderPlot({
  tab <- t(dat[,lapply(X=.SD,FUN="miss.value")])
  
  tab2 <- data.table(var=names(dat),miss=as.numeric(tab))
  barplot(height=tab2$miss, names.arg=tab2$var,space=0.01, las=1,
          main="Missing Rate",ylab="Percentage", ylim=c(0,100),col="dodgerblue")
  text(x = -0.5 + 1.02*1:tab2[, .N], y = -15, labels = tab2$var,srt = 45, cex = 1, pos = 2)
  space_val=0
  text(x=-0.4+1:length(tab)*(1+space_val),y=tab,labels=sprintf("%.1f%%",tab),pos=3)
})
```


Variable Information (designation vs. grape variety)
=====================================  


Row {data-height=800}
-------------------------------------



```{r}
inputPanel(
  checkboxInput(inputId = "show.percentage",label = "Show Percentage:",value = T),
  numericInput(inputId = "designation.number" ,label = "Designation Numbers:",value =3, min = 3,max = 15,step =1)
)


renderPlot({
  library(ggplot2)
  library(ggthemes)
  variety <- dat[,.(variety.number = length(unique(get(variety.name)))),by = designation.name]
  variety <- variety[-3,]
  setorderv(variety,cols = colnames(variety)[2],-1)
  
  data1 <- variety[1:input$designation.number,]
  
  if(input$show.percentage == TRUE){
    tab1 <- variety[,.(percentage.variety = percentage.cal(variety.number))]
    
    tab2 <- data.table(var = variety[1:input$designation.number,1], 
                       percentage = as.numeric(tab1$percentage.variety)[1:input$designation.number])
    space_val = 0
    text(x = -0.4 + 1:input$designation.number * (1+space_val), 
         y = tab1$percentage.variety[1:input$designation.number], 
         labels = sprintf("%.1f%%", tab1$percentage.variety[1:input$designation.number]), pos = 3)
    
  }
  
  ggplot(data=data1,aes(designation,variety.number,fill=designation))+
  geom_bar(stat = "identity",position = "dodge")+
  theme_wsj()+
  theme(axis.ticks.length=unit(0.5,'cm'))+
  guides(fill=guide_legend(title=NULL))+
  theme(axis.title = element_blank())+
  ggtitle("Number of Grape Variety ")
  
})


```

Variable Information (price vs. grape variety)
=====================================  


Row {data-height=800}
-------------------------------------

```{r}

inputPanel(
  numericInput(inputId = "variety.number" ,label = "Grape Variety:",value =3, min = 3,max = 20,step =1)
)



renderPlot({
  library(ggplot2)
  library(plotly)
  
  data2 <-dat[,length(get(variety.name)),by=get(variety.name)]
  setnames(data2,old=c("get","V1"), new = c("variety","number"))
  setorderv(data2,"number",-1)
  order.variety <-data2[,1]
  data3 <- dat[,get(price.name),by=get(variety.name)]
  setnames(data3,old=c("get","V1"), new = c("variety","price"))
  
  order.price.variety <-merge(data3,data2,by.x = "variety",by.y = "variety", all=T)
  setorderv(order.price.variety,cols = "number",-1)
  
  orders <- order.variety[1:input$variety.number,]$variety
  dat.new <- order.price.variety[order.price.variety$variety %in% orders]

  ggplot(dat.new, aes(variety, price, fill = variety)) + 
    geom_boxplot(notch = T,notchwidth = 0.5) + 
    ggtitle("Variety vs. Price") +
    theme(plot.title = element_text(hjust = 0.5))+
    labs(x="Grape Variety (Sorted from most to least)",y="Price") +
    #geom_violin()+
    scale_fill_brewer(palette = "Accent") +
    labs(fill = "variety")+
    scale_y_continuous(breaks=c(25,50))+
    ylim(0,150)
})

```



