---
title: "NLP"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library, include=FALSE}
library(data.table)
library(DT)
library(tidyverse)
library(tidytext)
#library(qdap)
library(ggthemes)
library(wordcloud)
library(RColorBrewer)
library(corrplot)
library(ggplot2)
```


```{r read data, echo=FALSE}
wine <- fread(input = 'wine.csv',verbose = FALSE,na.strings=c(""))
```

```{r constants}
country.name <- "country"
description.name <- "description"           
designation.name <- "designation"           
points.name <- "points"               
price.name <- "price"                 
province.name <- "province"              
region_1.name <- "region_1"              
region_2.name <- "region_2"             
taster.name <- "taster_name"           
twitter.name <- "taster_twitter_handle" 
title.name <- "title"                 
variaty.name <- "variety"              
winery.name <- "winery"               
wine[,eval(points.name)] <- as.numeric(wine[,get(points.name)])
wine[,eval(price.name)] <- as.numeric(wine[,get(price.name)])
```

```{r}
## create formula
create.formula <- function(outcome.name, input.names, input.patterns=NA, all.data.names=NA, return.as="character"){
  variable.names.from.patterns <- c()
  if (!is.na(input.patterns[1]) & !is.na(all.data.names[1])) {
    pattern <- paste(input.patterns, collapse = "|")
    variable.names.from.patterns <- all.data.names[grep(pattern = pattern, x = all.data.names)]
  }
  all.input.names <- unique(c(input.names, variable.names.from.patterns))
  all.input.names <- all.input.names[all.input.names !=outcome.name]
  if (!is.na(all.data.names[1])) {
    all.input.names <- all.input.names[all.input.names %in% all.data.names]
  }
  input.names.delineated <- sprintf("`%s`", all.input.names)
  the.formula <- sprintf("`%s` ~ %s", outcome.name, paste(input.names.delineated, collapse = " + "))
  if (return.as == "formula") {
    return(as.formula(the.formula))
  }
  if (return.as != "formula") {
    return(the.formula)
  }
}

reduce.formula <- function(dat, the.initial.formula, max.categories = NA) {
  require(data.table)
  dat <- setDT(dat)
  
  the.sides <- strsplit(x = the.initial.formula, split = "~")[[1]]
  lhs <- trimws(x = the.sides[1], which = "both")
  lhs.original <- gsub(pattern = "`", replacement = "", x = lhs)
  if (!(lhs.original %in% names(dat))) {
    return("Error: Outcome variable is not in names(dat).")
  }
  the.pieces.untrimmed <- strsplit(x = the.sides[2], split = "+", fixed = TRUE)[[1]]
  the.pieces.untrimmed.2 <- gsub(pattern = "`", replacement = "", x = the.pieces.untrimmed, fixed = TRUE)
  the.pieces.in.names <- trimws(x = the.pieces.untrimmed.2, which = "both")

  the.pieces <- the.pieces.in.names[the.pieces.in.names %in% names(dat)]
  num.variables <- length(the.pieces)
  include.pieces <- logical(num.variables)
  
  for (i in 1:num.variables) {
    unique.values <- dat[, unique(get(the.pieces[i]))]
    num.unique.values <- length(unique.values)
    if (num.unique.values >= 2) {
      include.pieces[i] <- TRUE
    }
    if (!is.na(max.categories)) {
      if (dat[, is.character(get(the.pieces[i])) | is.factor(get(the.pieces[i]))] == TRUE) {
        if (num.unique.values > max.categories) {
          include.pieces[i] <- FALSE
        }
      }
    }
  }
  pieces.rhs <- sprintf("`%s`", the.pieces[include.pieces == TRUE])
  rhs <- paste(pieces.rhs, collapse = " + ")
  the.formula <- sprintf("%s ~ %s", lhs, rhs)
  return(the.formula)
}
```



```{r, warning=FALSE}
dat <- wine %>%
  select(points.name,price.name,description.name,country.name,province.name,variaty.name,winery.name)
var.name <- c("acidity","tannins","smooth","dry","creamy","tight","soft","firm","light","rich","crisp","ripe","fresh","aging","sweet","earthy","spice")
for (i in 1:length(var.name)){
  dat[,var.name[i] := 1*grepl(var.name[i], dat$description)]
}

```

```{r}
n <- nrow(dat)
dat[get(price.name)>100, eval(price.name)] <- 100
selected <- sample(1:n, size=0.7*n, replace=FALSE)
train <- dat[selected,]
test <- dat[-selected,]
```


```{r}
formula.points <- create.formula(outcome.name="points",input.names=names(dat)[8:24])
the.formula <- reduce.formula(dat = train, the.initial.formula = formula.points)
model <- lm(formula = the.formula, data=train)
summary(model)
```

```{r}
test$points.est <- predict(model,newdata=test)
test$points.diff <- test$points.est-test$points
ggplot(data = test,aes(x= points.diff,y=..density..)) + 
  geom_histogram(na.rm=TRUE,fill="royalblue4",bins=15) +
  theme_classic() +
  ggtitle('Description word length Distribution') + 
  xlab('Number of words used in Description') + 
  ylab('Number of Observations') + 
  theme(plot.title = element_text(hjust = 0.5)) 
```

```{r}
sum(abs(test$points.diff)<=2,na.rm=TRUE)/n
```


```{r}
formula.price <- create.formula(outcome.name="price",input.names=names(dat)[8:24])
the.formula.2 <- reduce.formula(dat = dat, the.initial.formula = formula.price)
model.2 <- lm(formula = the.formula.2, data=train)
summary(model.2)
```

```{r}
test$price.est <- predict(model.2,newdata=test)
test$price.diff <- test$price.est-test$price
ggplot(data = test,aes(x= price.diff,y=..density..)) + 
  geom_histogram(na.rm=TRUE,fill="royalblue4",bins=15) +
  theme_classic() +
  ggtitle('Description word length Distribution') + 
  xlab('Number of words used in Description') + 
  ylab('Number of Observations') + 
  theme(plot.title = element_text(hjust = 0.5))

```


```{r}
sum(abs(test$price.diff)<=10,na.rm=TRUE)/n
```



