---
title: "Recommendation System"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library, include=FALSE}
library(data.table)
library(tidyverse)
library(recommenderlab)
library(DT)
library(prettydoc)
```


```{r read data, echo=FALSE}
dat <- fread(input = '../Data/wine.clean.csv',verbose = FALSE,na.strings=c(""))
```

```{r constants}
points.name <- "points"
taster.name <- "taster_name"
variety.name <- "variety"

dat <- dat[, mean(get(points.name)), by = .(get(taster.name), get(variety.name))]
setnames(dat, old = c('get','get.1','V1'), new = c('Taster Name','Variety','Point'))

```

```{r}
# convert into a s4 class 
data_matrix <- as(dat, 'realRatingMatrix')
image(data_matrix[1:19,1:50])

```

## Popular methods 

```{r}
recommenderRegistry$get_entry("POPULAR", type ="realRatingMatrix")

# recommendation for normal data 
recom <- Recommender(data_matrix,method='POPULAR',parameter = list(normalize=NULL))
pred <- predict(recom,data_matrix, n = 5)

data.frame(mapply(c, getList(pred), getRatings(pred)))

```

```{r train and test split}

set.seed(256)
split <- sample(x = nrow(data_matrix),size = 0.8*nrow(data_matrix))
train <- data_matrix[split,]
test <- data_matrix[-split,]


mean(getRatings(data_matrix), na.rm = TRUE)
```


```{r}
recommenderRegistry$get_entry('UBCF', type = 'realRatingMatrix')
# recommendation for normal data 
recom4 <- Recommender(data_matrix,method='UBCF',parameter = list(method = 'Cosine'))
pred4 <- predict(recom4,data_matrix, type = 'ratingMatrix',n = 1)

as.data.frame(mapply(c, getList(pred4), 
                     getRatings(pred4), 
                     as.list(rowMeans(data_matrix, na.rm = TRUE))))

recom.ubcf.2 <- Recommender( data = getData(es, 'train'),
                             method = 'UBCF')

pred.ubcf.2 <- predict(recom.ubcf.2,newdata = getData(es, 'known'), type = 'ratings')

calcPredictionAccuracy(pred.ubcf.2, data = getData(es, 'unknown'))

```

Calculatea a similarity matrix 

```{r similarity matrix}

# similarity matrix using the euclidean distance 
round(similarity(normalize(train[1:7]),method = 'euclidean'),3)

# similarity matrix using the cosine distance
round(similarity(normalize(train[1:7]),method = 'cosine'),3)

# similarity matrix using the pearson distance
round(similarity(normalize(train[1:7]),method = 'pearson'),3)
```

# Built recommender 


```{r}
es <- evaluationScheme(data_matrix, method = 'split', train = 0.8, given = 5)

recom.ubcf.2 <- Recommender( data = getData(es, 'train'),
                             method = 'UBCF')

prediction <- predict(recom.ubcf.2, test)

calcPredictionAccuracy(pred.ibcf, data = getData(es, 'unknown'))
```



